services:
  - type: web
    name: telegram-bot-lanation
    runtime: node
    repo: https://github.com/votre-username/votre-repo
    branch: main
    buildCommand: npm install
    startCommand: node bot-complete.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: telegram-bot-lanation
          property: hostUrl
    healthCheckPath: /health
    autoDeploy: true